// <auto-generated />
using System;
using EFCoreStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230922122420_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreStore.Entities.Url", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VisitedTimes")
                        .HasColumnType("int");

                    b.HasKey("ShortUrl");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
